name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate and fix YAML
        run: |
          # Fix README.md YAML
          sed -i '1s/^/---\n/' README.md
          sed -i '2s/^/title: Documentation\n/' README.md
          sed -i '3s/^/cover: .gitbook\/assets\/Xcop.jpg\n/' README.md
          sed -i '4s/^/---\n/' README.md

      - name: Setup Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install GitBook
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3

      - name: Fix content issues
        run: |
          # Fix embed tags
          find . -name "*.md" -exec sed -i 's/{% embed url="\([^"]*\)" %}/[Embedded Content](\1)/g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endembed %}//g' {} \;

          # Fix hint tags
          find . -name "*.md" -exec sed -i 's/{% hint style=".*" %}/> **Note**: /g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endhint %}//g' {} \;

      - name: Build and deploy
        run: |
          gitbook install
          gitbook build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
