name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install GitBook and dependencies
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3
          npm install font-awesome gitbook-plugin-sidebar-style --save

      - name: Setup GitBook configuration
        run: |
          # Create book.json
          cat << 'EOF' > book.json
          {
            "plugins": [
              "theme-default",
              "hints",
              "sidebar-style",
              "fontsettings",
              "search"
            ],
            "pluginsConfig": {
              "sidebar-style": {
                "width": 300
              },
              "hints": {
                "info": "fa fa-info-circle",
                "warning": "fa fa-exclamation-triangle",
                "danger": "fa fa-times-circle"
              }
            }
          }
          EOF

          # Create custom CSS
          mkdir -p styles
          cat << 'EOF' > styles/website.css
          @import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css");
          .book .book-summary ul.summary li i {
            display: inline-block !important;
            width: 20px;
            margin-right: 8px;
          }
          .book .book-summary {
            background: #f7f7f7 !important;
          }
          EOF

      - name: Fix content syntax
        run: |
          # Convert hint tags
          find . -name "*.md" -exec sed -i 's/{% hint style=".*" %}/::: tip/g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endhint %}/:::/g' {} \;
          
          # Convert icons
          find . -name "*.md" -exec sed -i 's/icon:\([a-z-]\+\)/<i class="fa fa-\1"><\/i>/g' {} \;

      - name: Build and deploy
        run: |
          gitbook install
          gitbook build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
