name: Build and Deploy GitBook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Updated from Node 10 (EOL) to 16 LTS

      - name: Install GitBook CLI
        run: |
          npm install -g gitbook-cli
          gitbook fetch latest

      - name: Fix hint tags automatically  # 👈 NEW STEP
        run: |
          find . -name "*.md" -exec sed -i 's/{% hint style="info" %}/> **Note**: /g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endhint %}//g' {} \;
          echo "Hint tags replaced successfully"

      - name: Install GitBook plugins
        run: gitbook install

      - name: Build GitBook site
        run: gitbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
