name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install GitBook
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3
          npm install replace-in-file --save

      - name: Auto-replace icons with FontAwesome
        run: |
          # Install FontAwesome CSS
          mkdir -p .gitbook
          echo '@import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css");' > .gitbook/website.css

          # Replace all icon patterns
          npx replace-in-file --configFile=<(echo '{
            "files": "**/*.md",
            "from": /icon:([a-z-]+)/g,
            "to": "<i class=\"fas fa-$1\"></i>"
          }')

          # Additional common replacements
          npx replace-in-file --configFile=<(echo '{
            "files": "**/*.md",
            "from": [
              /Icon: projector/g,
              /icon-projector/g
            ],
            "to": [
              "<i class=\"fas fa-projector\"></i>",
              "<i class=\"fas fa-projector\"></i>"
            ]
          }')

      - name: Configure GitBook
        run: |
          cat << 'EOF' > book.json
          {
            "plugins": ["hints"],
            "pluginsConfig": {
              "hints": {
                "info": "ℹ️",
                "warning": "⚠️",
                "danger": "❌"
              }
            }
          }
          EOF

      - name: Build and deploy
        run: |
          gitbook install
          gitbook build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
