name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install GitBook and dependencies
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3
          npm install gitbook-plugin-advanced-emoji --save

      - name: Auto-fix all content issues
        run: |
          # 1. Convert embed tags to iframes
          find . -name "*.md" -exec sed -i 's/{% embed url="\([^"]*\)" %}/<iframe src="\1" width="100%" height="500px"><\/iframe>/g' {} \;
          
          # 2. Convert hint tags
          find . -name "*.md" -exec sed -i 's/{% hint style=".*" %}/::: tip/g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endhint %}/:::/g' {} \;
          
          # 3. Convert icons to emoji
          find . -name "*.md" -exec sed -i 's/icon:\([a-z-]\+\)/🔹/g' {} \;

      - name: Build and deploy
        run: |
          gitbook install
          gitbook build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
