name: Build and Deploy GitBook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install GitBook CLI
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3

      # Setup GitBook configuration
      - name: Configure GitBook
        run: |
          # Create book.json with proper github plugin config
          echo '{
            "plugins": [
              "theme-default",
              "hints",
              "github",
              "sidebar-style",
              "fontsettings",
              "search",
              "highlight",
              "lunr",
              "sharing"
            ],
            "pluginsConfig": {
              "github": {
                "url": "https://github.com/YOUR_USERNAME/YOUR_REPO"
              },
              "hints": {
                "info": "octicon octicon-info",
                "warning": "octicon octicon-alert",
                "danger": "octicon octicon-stop"
              }
            }
          }' > book.json
          
          # Create custom CSS
          mkdir -p .gitbook
          echo '/* GitHub Octicons styling */
          .book .book-summary ul.summary li i {
            display: inline-block !important;
            margin-right: 8px;
          }' > .gitbook/website.css

      # Fix content tags
      - name: Fix hint tags
        run: |
          find . -name "*.md" -exec sed -i 's/{% hint style=".*" %}/::: tip/g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endhint %}/:::/g' {} \;

      - name: Fix embed tags
        run: |
          find . -name "*.md" -exec sed -i 's/{% embed url="\([^"]*\)" %}/[View Content](\1)/g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endembed %}//g' {} \;

      - name: Install plugins
        run: gitbook install

      - name: Build site
        run: gitbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
