name: Build and Deploy GitBook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'  # Explicitly uses Node 10 for GitBook compatibility

      - name: Install GitBook CLI
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3  # Explicitly install GitBook 3.2.3 (stable with Node 10)

      - name: Fix hint tags automatically  # 👈 Replaces unsupported hint tags
        run: |
          find . -name "*.md" -exec sed -i 's/{% hint style=".*" %}/> **Note**: /g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endhint %}//g' {} \;

      - name: Install GitBook plugins
        run: gitbook install

      - name: Build GitBook site
        run: gitbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
