name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install GitBook with fixes
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3
          npm install gitbook-plugin-fontawesome --save

      - name: Configure styling
        run: |
          # Create proper book.json
          cat << 'EOF' > book.json
          {
            "title": "Xoop Documentation",
            "plugins": ["fontawesome", "hints", "-search", "theme-default"],
            "pluginsConfig": {
              "fontawesome": {
                "include": "all"
              },
              "hints": {
                "info": "fa fa-info-circle",
                "warning": "fa fa-exclamation-triangle",
                "danger": "fa fa-times-circle"
              }
            }
          }
          EOF

          # Create CSS fixes
          mkdir -p .gitbook
          cat << 'EOF' > .gitbook/website.css
          @import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css");
          
          /* Sidebar styling */
          .book .book-summary {
            width: 300px;
            background: #f7f7f7;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
          }
          
          /* Icon styling */
          .book .book-summary ul.summary li i {
            display: inline-block !important;
            width: 20px;
            margin-right: 10px;
            font-family: 'Font Awesome 6 Free' !important;
            font-weight: 900;
          }
          EOF

      - name: Transform content
        run: |
          # Convert icon markers to FontAwesome
          find . -name "*.md" -exec sed -i 's/icon:projector/<i class="fas fa-projector"><\/i>/g' {} \;
          find . -name "*.md" -exec sed -i 's/icon:([a-z-]+)/<i class="fas fa-\1"><\/i>/g' {} \;
          
          # Fix cover line
          find . -name "*.md" -exec sed -i 's/cover: gtbook\/assets\/Xoop\.jpg/cover: .gitbook\/assets\/Xoop.jpg/g' {} \;

      - name: Build and deploy
        run: |
          gitbook install
          gitbook build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
