name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 10 (GitBook compatible)
        uses: actions/setup-node@v3
        with:
          node-version: '10'
          cache: 'npm'

      - name: Install GitBook (stable combination)
        run: |
          npm install -g gitbook-cli@2.3.2
          gitbook fetch 3.2.2
          # Install only essential plugins
          npm install gitbook-plugin-hints@1.0.2 --save

      - name: Configure environment
        run: |
          # Create minimal config
          cat << 'EOF' > book.json
          {
            "title": "Xoop Documentation",
            "plugins": ["hints", "-search", "-lunr"],
            "pluginsConfig": {
              "hints": {
                "info": "📌",
                "warning": "⚠️",
                "danger": "❌"
              }
            }
          }
          EOF

          # Create CSS fixes (no external dependencies)
          mkdir -p .gitbook
          cat << 'EOF' > .gitbook/website.css
          /* GitBook.io exact styling */
          .book .book-summary {
            width: 300px !important;
            background: #f7f7f7 !important;
            font-family: -apple-system, sans-serif !important;
          }
          .book .book-summary li a:before {
            content: "•";
            color: #7e888b;
            margin-right: 10px;
          }
          /* Projector icon replacement */
          span.icon-projector:before {
            content: "📽️";
            margin-right: 5px;
          }
          EOF

      - name: Transform content
        run: |
          # Replace icon markers with spans
          find . -name "*.md" -exec sed -i 's/Icon: projector/<span class="icon-projector"><\/span>/g' {} \;
          
          # Fix cover path
          find . -name "*.md" -exec sed -i 's/cover: gtbook\/assets\/Xoop\.jpg/cover: .gitbook\/assets\/Xoop.jpg/g' {} \;
          
          # Convert hints to simple blocks
          find . -name "*.md" -exec sed -i 's/{% hint style=".*" %}/> /g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endhint %}//g' {} \;

      - name: Build site
        run: |
          gitbook install
          gitbook build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
