name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Updated from Node 10 which is deprecated

      - name: Install dependencies
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3
          npm install replace-in-file --save-dev
          npm install @fortawesome/fontawesome-free --save-dev

      - name: Set up FontAwesome and custom styles
        run: |
          # Create custom CSS directory
          mkdir -p .gitbook/styles
          
          # Copy FontAwesome CSS
          cp node_modules/@fortawesome/fontawesome-free/css/all.min.css .gitbook/styles/
          
          # Create custom CSS file
          echo '@import "styles/all.min.css";' > .gitbook/website.css
          echo 'i.fas { margin-right: 5px; }' >> .gitbook/website.css

      - name: Replace icon patterns
        run: |
          # Replace icon patterns with FontAwesome icons
          npx replace-in-file \
            --files="**/*.md" \
            --from='icon:([a-z-]+)' \
            --to='<i class="fas fa-$1"></i>'
          
          # Additional common replacements
          npx replace-in-file \
            --files="**/*.md" \
            --from='icon-projector' \
            --to='<i class="fas fa-projector"></i>'

      - name: Configure GitBook
        run: |
          cat << 'EOF' > book.json
          {
            "plugins": ["hints"],
            "pluginsConfig": {
              "hints": {
                "info": "ℹ️",
                "warning": "⚠️",
                "danger": "❌"
              }
            },
            "styles": {
              "website": "styles/website.css"
            }
          }
          EOF

      - name: Build GitBook
        run: |
          gitbook install
          gitbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
