name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install GitBook and dependencies
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3
          npm install gitbook-plugin-hints gitbook-plugin-theme-comscore --save

      - name: Setup GitBook configuration
        run: |
          # Create minimal book.json without github plugin
          echo '{
            "plugins": ["hints", "theme-comscore"],
            "pluginsConfig": {
              "hints": {
                "info": "💡",
                "warning": "⚠️",
                "danger": "❌"
              }
            }
          }' > book.json
          # Create exact GitBook.io styling
          mkdir -p styles
          cat << 'EOF' > styles/website.css
          /* Exact GitBook.io sidebar styling */
          .book .book-summary {
            width: 300px;
            background: #f7f7f7;
            border-right: 1px solid #eaeaea;
          }
          
          /* GitBook.io icon styling */
          .book .book-summary ul.summary li a:before {
            content: "•";
            margin-right: 10px;
            color: #7e888b;
          }
          
          /* Content area matching GitBook.io */
          .book .book-body {
            color: #3c484e;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, sans-serif;
          }
          EOF

      - name: Convert all legacy syntax
        run: |
          # 1. Convert embed tags to simple links
          find . -name "*.md" -exec sed -i 's/{% embed url="\$[^"]*\$" %}/[View Content](\1)/g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endembed %}//g' {} \;
          
          # 2. Convert hint tags to emoji blocks
          find . -name "*.md" -exec sed -i 's/{% hint style="info" %}/💡 /g' {} \;
          find . -name "*.md" -exec sed -i 's/{% hint style="warning" %}/⚠️ /g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endhint %}//g' {} \;
          
          # 3. Remove unsupported icon syntax
          find . -name "*.md" -exec sed -i 's/icon:[a-z-]*//g' {} \;

      - name: Build the GitBook
        run: |
          gitbook install
          gitbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
