name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install GitBook
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.2
          
      - name: Create book.json with icon plugins
        run: |
          cat << 'EOF' > book.json
          {
            "title": "Your Documentation",
            "plugins": [
              "-search", 
              "fontsettings", 
              "theme-default",
              "fontawesome",
              "custom-favicon"
            ],
            "pluginsConfig": {
              "fontsettings": {
                "theme": "white"
              },
              "fontawesome": {
                "version": "6.4.0"
              }
            }
          }
          EOF
          
      - name: Create enhanced styles with better icon support
        run: |
          mkdir -p styles
          cat << 'EOF' > styles/website.css
          /* Import Font Awesome */
          @import url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css');
          
          /* Force sidebar to show */
          .book .book-summary {
            position: fixed !important;
            top: 0 !important;
            left: 0 !important;
            bottom: 0 !important;
            width: 300px !important;
            background: #fafafa !important;
            border-right: 1px solid #e7e7e7 !important;
            overflow-y: auto !important;
            z-index: 1000 !important;
            display: block !important;
          }
          
          .book .book-body {
            position: absolute !important;
            top: 0 !important;
            right: 0 !important;
            left: 300px !important;
            bottom: 0 !important;
            overflow-y: auto !important;
          }
          
          .book .book-summary ul.summary {
            list-style: none !important;
            margin: 0 !important;
            padding: 20px 0 !important;
          }
          
          .book .book-summary li a {
            display: block !important;
            padding: 8px 20px !important;
            color: #364149 !important;
            text-decoration: none !important;
            position: relative !important;
          }
          
          .book .book-summary li a:hover {
            background: #f3f3f3 !important;
            color: #008cff !important;
          }
          
          .book .book-summary li.active > a {
            color: #008cff !important;
            background: #f3f3f3 !important;
            font-weight: 600 !important;
          }
          
          /* Enhanced Font Awesome support */
          .fa, [class^="fa-"], [class*=" fa-"] {
            font-family: "Font Awesome 6 Free" !important;
            font-weight: 900 !important;
          }
          
          .fab {
            font-family: "Font Awesome 6 Brands" !important;
            font-weight: 400 !important;
          }
          
          .far {
            font-family: "Font Awesome 6 Free" !important;
            font-weight: 400 !important;
          }
          
          /* Custom navigation icons based on content */
          .book .book-summary li a[href*="getting-started"]:before {
            content: "\f135" !important; /* rocket */
            font-family: "Font Awesome 6 Free" !important;
            font-weight: 900 !important;
            margin-right: 8px !important;
            color: #28a745 !important;
          }
          
          .book .book-summary li a[href*="theme"]:before {
            content: "\f53f" !important; /* palette */
            font-family: "Font Awesome 6 Free" !important;
            font-weight: 900 !important;
            margin-right: 8px !important;
            color: #6f42c1 !important;
          }
          
          .book .book-summary li a[href*="header"]:before {
            content: "\f0c9" !important; /* bars */
            font-family: "Font Awesome 6 Free" !important;
            font-weight: 900 !important;
            margin-right: 8px !important;
            color: #007bff !important;
          }
          
          .book .book-summary li a[href*="support"]:before {
            content: "\f1cd" !important; /* life-ring */
            font-family: "Font Awesome 6 Free" !important;
            font-weight: 900 !important;
            margin-right: 8px !important;
            color: #dc3545 !important;
          }
          
          .book .book-summary li a[href*="install"]:before {
            content: "\f019" !important; /* download */
            font-family: "Font Awesome 6 Free" !important;
            font-weight: 900 !important;
            margin-right: 8px !important;
            color: #fd7e14 !important;
          }
          
          /* Default icon for other pages */
          .book .book-summary li a:not([href*="getting-started"]):not([href*="theme"]):not([href*="header"]):not([href*="support"]):not([href*="install"]):before {
            content: "\f15c" !important; /* file */
            font-family: "Font Awesome 6 Free" !important;
            font-weight: 900 !important;
            margin-right: 8px !important;
            color: #7e888b !important;
          }
          
          /* Content area icon styling */
          .markdown-section .fa, 
          .markdown-section [class^="fa-"], 
          .markdown-section [class*=" fa-"] {
            margin-right: 0.5em !important;
            vertical-align: middle !important;
          }
          
          /* Icon boxes for callouts */
          .icon-box {
            display: flex !important;
            align-items: center !important;
            padding: 15px !important;
            margin: 20px 0 !important;
            border-radius: 8px !important;
            border-left: 4px solid !important;
          }
          
          .icon-box.info {
            background-color: #e7f3ff !important;
            border-left-color: #007bff !important;
          }
          
          .icon-box.warning {
            background-color: #fff3cd !important;
            border-left-color: #ffc107 !important;
          }
          
          .icon-box.success {
            background-color: #d4edda !important;
            border-left-color: #28a745 !important;
          }
          
          .icon-box.danger {
            background-color: #f8d7da !important;
            border-left-color: #dc3545 !important;
          }
          
          .icon-box i {
            font-size: 1.5em !important;
            margin-right: 15px !important;
            flex-shrink: 0 !important;
          }
          
          /* Mobile responsive */
          @media (max-width: 1240px) {
            .book .book-summary {
              left: -300px !important;
              transition: left 0.3s ease !important;
            }
            
            .book .book-summary.mobile-open {
              left: 0 !important;
            }
            
            .book .book-body {
              left: 0 !important;
            }
          }
          EOF
          
      - name: Create icon replacement script
        run: |
          mkdir -p assets
          cat << 'EOF' > assets/icon-replacer.js
          window.addEventListener('load', function() {
            console.log('Icon replacer loaded');
            
            // Replace common text patterns with Font Awesome icons
            function replaceTextWithIcons() {
              const content = document.querySelector('.markdown-section');
              if (!content) return;
              
              let html = content.innerHTML;
              
              // Replace common patterns
              html = html.replace(/\[icon:info\]/g, '<i class="fas fa-info-circle" style="color: #007bff;"></i>');
              html = html.replace(/\[icon:warning\]/g, '<i class="fas fa-exclamation-triangle" style="color: #ffc107;"></i>');
              html = html.replace(/\[icon:success\]/g, '<i class="fas fa-check-circle" style="color: #28a745;"></i>');
              html = html.replace(/\[icon:error\]/g, '<i class="fas fa-times-circle" style="color: #dc3545;"></i>');
              html = html.replace(/\[icon:download\]/g, '<i class="fas fa-download" style="color: #fd7e14;"></i>');
              html = html.replace(/\[icon:link\]/g, '<i class="fas fa-external-link-alt" style="color: #6c757d;"></i>');
              html = html.replace(/\[icon:code\]/g, '<i class="fas fa-code" style="color: #6f42c1;"></i>');
              html = html.replace(/\[icon:settings\]/g, '<i class="fas fa-cog" style="color: #6c757d;"></i>');
              html = html.replace(/\[icon:user\]/g, '<i class="fas fa-user" style="color: #6c757d;"></i>');
              html = html.replace(/\[icon:home\]/g, '<i class="fas fa-home" style="color: #28a745;"></i>');
              
              // Replace callout boxes
              html = html.replace(/\[info\](.*?)\[\/info\]/gs, '<div class="icon-box info"><i class="fas fa-info-circle"></i><div>$1</div></div>');
              html = html.replace(/\[warning\](.*?)\[\/warning\]/gs, '<div class="icon-box warning"><i class="fas fa-exclamation-triangle"></i><div>$1</div></div>');
              html = html.replace(/\[success\](.*?)\[\/success\]/gs, '<div class="icon-box success"><i class="fas fa-check-circle"></i><div>$1</div></div>');
              html = html.replace(/\[danger\](.*?)\[\/danger\]/gs, '<div class="icon-box danger"><i class="fas fa-times-circle"></i><div>$1</div></div>');
              
              content.innerHTML = html;
            }
            
            // Run replacement
            replaceTextWithIcons();
            
            // Add mobile toggle button
            if (window.innerWidth <= 1240) {
              var toggleBtn = document.createElement('button');
              toggleBtn.innerHTML = '<i class="fas fa-bars"></i>';
              toggleBtn.style.cssText = 'position: fixed; top: 10px; left: 10px; z-index: 2000; background: #fff; border: 1px solid #ccc; padding: 10px; cursor: pointer; border-radius: 4px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);';
              
              toggleBtn.addEventListener('click', function() {
                var summary = document.querySelector('.book-summary');
                if (summary) {
                  summary.classList.toggle('mobile-open');
                }
              });
              
              document.body.appendChild(toggleBtn);
            }
          });
          EOF
          
      - name: Create example markdown with icons
        run: |
          cat << 'EOF' > EXAMPLE_ICONS.md
          # Icon Usage Examples
          
          ## Simple Icons
          You can use these patterns in your markdown files:
          
          - [icon:info] Information icon
          - [icon:warning] Warning icon  
          - [icon:success] Success icon
          - [icon:error] Error icon
          - [icon:download] Download icon
          - [icon:link] External link icon
          - [icon:code] Code icon
          - [icon:settings] Settings icon
          - [icon:user] User icon
          - [icon:home] Home icon
          
          ## Callout Boxes
          
          [info]
          This is an information callout box with an icon.
          [/info]
          
          [warning]
          This is a warning callout box with an icon.
          [/warning]
          
          [success]
          This is a success callout box with an icon.
          [/success]
          
          [danger]
          This is a danger callout box with an icon.
          [/danger]
          
          ## Direct HTML (Alternative)
          You can also use HTML directly:
          
          <i class="fas fa-star" style="color: gold;"></i> Gold star
          <i class="fab fa-github"></i> GitHub icon
          <i class="far fa-heart"></i> Heart outline
          EOF
          
      - name: Build GitBook
        run: |
          gitbook install
          gitbook build
          
      - name: Add scripts and icons to HTML files
        run: |
          # Add Font Awesome and icon replacer script to all HTML files
          find ./_book -name "*.html" -exec sed -i 's|</head>|<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\"><script src=\"assets/icon-replacer.js\"></script></head>|g' {} \;
          
          # Copy scripts to _book
          cp assets/icon-replacer.js ./_book/assets/icon-replacer.js
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
