name: Build and Deploy GitBook

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 10
        uses: actions/setup-node@v3
        with:
          node-version: '10'

      - name: Install GitBook
        run: |
          npm install -g gitbook-cli
          gitbook fetch 3.2.3

      - name: Create error-free configuration
        run: |
          # Minimal book.json without github plugin
          cat << 'EOF' > book.json
          {
            "title": "Your Documentation",
            "plugins": ["hints", "search", "fontsettings"],
            "pluginsConfig": {
              "hints": {
                "info": "ℹ️",
                "warning": "⚠️", 
                "danger": "❌"
              }
            }
          }
          EOF

          # Fix README.md YAML
          sed -i '1s/^/---\ntitle: Documentation\ncover: .gitbook\/assets\/Xcop.jpg\n---\n/' README.md

      - name: Apply all content fixes
        run: |
          # 1. Convert embeds to links
          find . -name "*.md" -exec sed -i 's/{% embed url="\([^"]*\)" %}/[View Content](\1)/g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endembed %}//g' {} \;

          # 2. Convert hints to callouts
          find . -name "*.md" -exec sed -i 's/{% hint style="info" %}/> **ℹ️ Note**: /g' {} \;
          find . -name "*.md" -exec sed -i 's/{% hint style="warning" %}/> **⚠️ Warning**: /g' {} \;
          find . -name "*.md" -exec sed -i 's/{% endhint %}//g' {} \;

          # 3. Remove icon syntax
          find . -name "*.md" -exec sed -i 's/icon:[a-z-]*//g' {} \;

      - name: Add GitBook.io styling
        run: |
          mkdir -p .gitbook
          cat << 'EOF' > .gitbook/website.css
          /* Exact GitBook.io styling */
          .book .book-summary {
            width: 300px;
            background: #f7f7f7;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
          }
          .book .book-summary li a:before {
            content: "•";
            color: #7e888b;
            margin-right: 10px;
          }
          EOF

      - name: Build and deploy
        run: |
          gitbook install
          gitbook build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
