name: Build and Deploy GitBook

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build GitBook site using Docker (Node 14)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace node:14 bash -c "
            npm install -g gitbook-cli &&
            gitbook install &&
            gitbook build
          "

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
